name: CI - Run Tests and SonarQube Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.13.0
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Install client dependencies
        run: npm ci --prefix ./client

      - name: Run Jest tests (without coverage)
        run: |
          npm run test:backend -- --coverage=false
          npm run test:frontend -- --coverage=false

  coverage:
    name: Check Coverage and Run SonarQube Analysis
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.13.0
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Install client dependencies
        run: npm ci --prefix ./client

      - name: Run Backend Jest tests with coverage
        run: npm run test:backend
        continue-on-error: true
        id: jest-test-backend

      - name: Run Frontend (client) Jest tests with coverage
        run: npm run test:frontend
        continue-on-error: true
        id: jest-test-frontend

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Fail if any Jest Coverage check failed
        if: steps.jest-test-backend.outcome == 'failure' || steps.jest-test-frontend.outcome == 'failure'
        run: exit 1
